" vim: spell filetype=vim:
set nocompatible
filetype off

" Functions definition {{{
" Strip whitespace {{{
function! StripTrailingWhitespace()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " do the business:
    %s/\s\+$//e
    " clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
" }}}

" Shell command {{{
function! s:RunShellCommand(cmdline)
    botright new

    setlocal buftype=nofile
    setlocal bufhidden=delete
    setlocal nobuflisted
    setlocal noswapfile
    setlocal nowrap
    setlocal filetype=shell
    setlocal syntax=shell

    call setline(1, a:cmdline)
    call setline(2, substitute(a:cmdline, '.', '=', 'g'))
    execute 'silent $read !' . escape(a:cmdline, '%#')
    setlocal nomodifiable
    1
endfunction

command! -complete=file -nargs=+ Shell call s:RunShellCommand(<q-args>)
" e.g. Grep current file for <search_term>: Shell grep -Hn <search_term> %
" }}}
" }}}

" Load user Pre-Configuration {{{
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif
" }}}

" Plugins {{{ 
" Requirements {{{ 
    set nocompatible
    set background=dark
" }}}

" Setup vim-plug {{{
    call plug#begin("~/.vim/bundle")
" }}}

" Bundle Dependencies

" Vim utility functions {{{
    Plug 'tomtom/tlib_vim'
    Plug 'MarcWeber/vim-addon-mw-utils'
" }}}

" ACK Bundle setup {{{
    if executable('ack')
        Plug 'mileszs/ack.vim'
    endif
" }}}

" NerdTree {{{
    Plug 'scrooloose/nerdtree'
    let NERDTreeShowBookmarks=1
    let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$']
    let NERDTreeChDirMode=0
    let NERDTreeQuitOnOpen=1
    let NERDTreeMouseMode=2
    let NERDTreeShowHidden=1
    let NERDTreeKeepTreeInNewTab=1
    let g:nerdtree_tabs_open_on_gui_startup=0
" }}}

" Dark Solarized theme {{{
" https://github.com/w0ng/vim-hybrid
    Plug 'hybrid.vim'
    let g:hybrid_use_Xresources=1
" }}}

" Regular Solarized theme {{{
    Plug 'altercation/vim-colors-solarized'
" }}}

" Color schemes {{{
    Plug 'spf13/vim-colors'
    Plug 'flazz/vim-colorschemes'
" }}}

" Quote and tags (surroundings) {{{
" https://github.com/tpope/vim-surround
    Plug 'tpope/vim-surround'
" }}}

" Expand visual selection {{{
" https://github.com/terryma/vim-expand-region
    Plug 'terryma/vim-expand-region'
" }}}

" Automatically close pair-characters {{{
" https://github.com/spf13/vim-autoclose
    Plug 'spf13/vim-autoclose'
    let g:autoclose_vim_commentmode=1 " Do not autoclose '"' in vimscript
" }}}

" CtrlP: Fuzzy finder (file, path, buffer, etc) {{{
" http://ctrlpvim.github.io/ctrlp.vim/
    Plug 'ctrlpvim/ctrlp.vim'
    let g:ctrlp_working_path_mode = 'ra'
    let g:ctrlp_custom_ignore ={
        \ 'dir': '\.(git|hg|svn)$',
        \ 'file': '\.(so|pyc)$',
        \ }

    let s:ctrlp_fallback = 'ag %s --nocolor -f'
     let g:ctrlp_user_command = {
                \ 'types': {
                    \ 1: ['.git', 'cd %s && git ls-files . --cached --exclude-standard --others'],
                    \ 2: ['.hg', 'hg --cwd %s locate -I .'],
                \ },
                \ 'fallback': s:ctrlp_fallback
            \ }
" }}}

" Sublime-like Multiple selections {{{
" https://github.com/terryma/vim-multiple-cursors
    Plug 'kristijanhusak/vim-multiple-cursors'
" }}}

" Buffer list in statusline {{{
" https://github.com/bling/vim-bufferline
    Plug 'bling/vim-bufferline'
    let g:bufferline_active_buffer_left = ''
    let g:bufferline_active_buffer_right = ''
" }}}

" Lighline: Statusline-light {{{
" https://github.com/itchyny/lightline.vim
    Plug 'itchyny/lightline.vim'
    set laststatus=2

    let g:lightline = {
        \ 'active': {
        \   'left': [ [ 'mode', 'paste'], [ 'filename' ], [ 'bufferline' ] ],
        \ },
        \ 'separator': { 'left': '', 'right': '' },
        \ 'subseparator': { 'left': '', 'right': '' },
        \ 'component': {
        \   'bufferline': '%{bufferline#refresh_status()}%{g:bufferline_status_info.before}%#TabLineSel#%{g:bufferline_status_info.current}%#LightLineLeft_active_3#%{g:bufferline_status_info.after}'
        \ }
    \ }
" }}}

" EasyMotion, Vim motion with highlighting {{{
" https://github.com/Lokaltog/vim-easymotion
    Plug 'Lokaltog/vim-easymotion'
" }}}

" NERDTree + Tabs fix {{{
" https://github.com/jistr/vim-nerdtree-tabs
    Plug 'jistr/vim-nerdtree-tabs'
" }}}

" NERDCommenter: Comments helper {{{
" https://github.com/scrooloose/nerdcommenter
    Plug 'scrooloose/nerdcommenter'
" }}} 

" UndoTree {{{
" https://github.com/mbbill/undotree
    Plug 'mbbill/undotree'
    let g:undotree_SetFocusWhenToggle=1
" }}}

" Abolish: Easy Substitution {{{
" https://github.com/tpope/vim-abolish
    Plug 'tpope/vim-abolish'
" }}}

" Tabular: Aligning text {{{
" https://github.com/godlygeek/tabular
    Plug 'godlygeek/tabular'
" }}}

" Tagbar: Class outline {{{
" http://majutsushi.github.io/tagbar
    Plug 'majutsushi/tagbar'
" }}}

" YouCompleteMe: Code-completion engine{{{
" http://valloric.github.io/YouCompleteMe/"
    if !exists('g:disable_ycm')
        Plug 'Valloric/YouCompleteMe', { 'do': './install.sh'}
    endif
" }}}

" UltiSnips: Snippets auto-complete {{{
    if v:version > 703
        Plug 'SirVer/ultisnips'
        Plug 'honza/vim-snippets'
    endif
" }}}

" Split window horizontally {{{
    let g:UltiSnipsEditSplit="vertical"
" }}}

" Twig Syntax Highlighting {{{
" https://github.com/beyondwords/vim-twig
    Plug 'beyondwords/vim-twig'
" }}}

" vim-php-namespace {{{
    Plug 'arnaud-lb/vim-php-namespace'
" }}}

" HTML-AutoCloseTag: Automatically close html tags {{{
" https://github.com/amirh/HTML-AutoCloseTag
    Plug 'amirh/HTML-AutoCloseTag'
" }}}

" CSS3-Syntax: Add CSS3 Syntax highlighting {{{
" https://github.com/hail2u/vim-css3-syntax
    Plug 'hail2u/vim-css3-syntax', { 'for': 'css' }
" }}}

" HTML Color preview {{{
" https://github.com/gorodinskiy/vim-coloresque
    Plug 'gorodinskiy/vim-coloresque'
" }}}

" Javascript Syntax Support Enhanced {{{
" https://github.com/pangloss/vim-javascript
    Plug 'pangloss/vim-javascript'
" }}}

" Better JSON support {{{
" https://github.com/elzr/vim-json
    Plug 'elzr/vim-json', { 'for': 'json' }
" }}}

" GitGutter: Git diff in gutter {{{
" https://github.com/airblade/vim-gitgutter
    Plug 'airblade/vim-gitgutter'
" }}}

" Lisp-like {{{
    Plug 'kien/rainbow_parentheses.vim', { 'for': ['clojure', 'racket', 'lisp'] }
" }}}

" Ruby {{{
    if !exists('g:disable_ruby_plugins')
" Awesome Rails navigation {{{
" https://github.com/tpope/vim-rails
        Plug 'tpope/vim-rails', { 'for': 'ruby' }
" }}}

" Lightweight Bundler wrapper {{{
" https://github.com/tpope/vim-bundler
        Plug 'tpope/vim-bundler', { 'for': 'ruby' }
" }}}

" Rake helper {{{
" https://github.com/tpope/vim-rake
        Plug 'https://github.com/tpope/vim-rake.git', { 'for': 'ruby' }
" }}}
" Project configuration (rake.vim dependencies) {{{
" https://github.com/tpope/vim-projectionist
        Plug 'https://github.com/tpope/vim-projectionist.git', { 'for': 'ruby' }
" }}}
        let g:rubycomplete_buffer_loading = 1
    endif
" }}}

" Python {{{
    if !exists('g:disable_python_plugins')
" Python-mode {{{ 
" https://github.com/klen/python-mode
        Plug 'klen/python-mode'
" }}}
    endif
" }}}

" Unite: Buffer helper {{{
    Plug 'shougo/unite.vim'
" }}}

" autotag: Automatically update ctags {{{
" https://github.com/craigemery/vim-autotag
    Plug 'https://github.com/craigemery/vim-autotag.git'
" }}}
call plug#end()
" }}}

" General Settings {{{
filetype plugin indent on " Detect file types
syntax on                 " Syntax highlighting
set mouse=""              " I don't want no stinking mouse
scriptencoding utf-8      " Set encoding to utf-8

set history=1000          " Increase history size
set spell                 " Enable Spell-check
set hidden                " Enable buffer switch without saving
set iskeyword-=.          " '.' represents a word
set iskeyword-=#          " '#' represents a word
set iskeyword-=-          " '-' represents a word

set backspace=indent,eol,start " What to delete on backspace
set foldenable                 " Auto-fold
set hlsearch                   " Highlight search term
set ignorecase                 " Default search is case-insensitive
set incsearch                  " Search as you type
set linespace=0                " No extra space between rows
set nu                         " Line numbering
set scrolljump=5               " Jump 5 lines when cursor leave screen
set scrolloff=3                " Minimum lines above or below cursor
set shortmess+=aoOtT           " Abbreviate messages
set showmatch                  " Show matching brackets/parenthesis
set smartcase                  " When uppercase detected, search case-sensitive
set whichwrap=b,s,h,l,<,>,[,]  " Cursor + backspace + default wrap
set wildmenu                   " Display menu instead of auto-complete
set wildmode=list:longest,full " Tab completion order
set winminheight=0             " Window can be any size

set list
set listchars=tab:>\ ,trail:•,extends:#,nbsp:. " Replace special chars in list mode
" }}}

" Temporary files directories {{{
" Double slash prevents name collision
    " Backup {{{
    set backupdir=~/.vim/backup
    set backupdir+=~/.vim-backup
    set backupdir+=.
    set backup
    set writebackup
    " }}}

    " Swap {{{
    set directory=./.vim-swap//
    set directory+=~/.vim/swap//
    set directory+=.
    " }}}

    " Undo {{{
    if has("persistent_undo")
        set undodir=~/.vim/undo//
        set undofile
    endif 
    " }}}
" }}}

" Formatting {{{
set nowrap            " No line wrapping
set autoindent        " Indent according to previous line
set shiftwidth=4      " Use 4-spaces indent
set expandtab         " Tabs are spaces, No thank you tabs
set tabstop=4         " Indentation is 4 columns
set softtabstop=4     " Backspace delete indent
set nojoinspaces      " Don't include space after join
set splitright        " vsplit to the right of current
set splitbelow        " hsplit below current
set pastetoggle=<F12> " Sane indentation on paste
" }}}

" Autocommands {{{
    " Remove trailing whitespace"{{{
    augroup trailing_whitespace
        autocmd FileType c,cpp,java,go,php,javascript,puppet,python,rust,twig,xml,yml,perl,sql autocmd BufWritePre <buffer> | call StripTrailingWhitespace()
    augroup END
    " }}}

    " Markdown filetype {{{
    augroup filetype_md
        autocmd BufNewFile,BufReadPost *.md set filetype=markdown
    augroup END
    " }}}

    " Vim filetype {{{
    augroup filetype_vim
        autocmd!
        autocmd FileType vim setlocal foldmethod=marker
    augroup END
    " }}}
" }}}

" Vim UI {{{
set showmode            " Display active mode
set cursorline          " Highlight current line

if !has('gui_running')
  set t_Co=256
endif
" }}}

" Fix Shift mistakes {{{
if has("user_commands")
    command! -bang -nargs=* -complete=file E  e<bang> <args>
    command! -bang -nargs=* -complete=file W  w<bang> <args>
    command! -bang -nargs=* -complete=file Wq wq<bang> <args>
    command! -bang -nargs=* -complete=file WQ QW<bang> <args>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Q  q<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>
endif
" }}}

" Keymappings {{{
    " Leader key {{{
    let mapleader = ','
    " }}}

    " Return to normal mode {{{
    inoremap jk <esc>
    " }}}

    " Expand visual selection {{{
    vmap v <Plug>(expand_region_expand)
    vmap <C-v> <Plug>(expan_region_shrink)
    " }}}

    " Forgot sudo? {{{
    cmap w!! w !sudo tee % >/dev/null
    " }}}

    " Edit mode helper {{{
    cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>
    map <leader>ew :e   %%
    map <leader>es :sp  %%
    map <leader>ev :vsp %%
    " }}}

    " NERDTree {{{
    map    <C-e>        <plug>NERDTreeTabsToggle<CR>
    map    <leader>e    :NERDTreeFind<CR>
    nmap   <leader>nt   :NERDTreeFind<CR>
    " }}}

    " Tagbar {{{
    nnoremap <silent> <leader>tt :TagbarToggle<Cr>
    nnoremap <silent> <leader>to :TagbarOpenAutoClose<Cr>
    " }}}

    " UndoTree {{{
    nnoremap <Leader>u :UndotreeToggle<CR>
    " }}}

    " Remap UltiSnips for compatibility with YouCompleteMe {{{
    let g:UltiSnipsExpandTrigger       = '<C-j>'
    let g:UltiSnipsJumpForwardTrigger  = '<C-j>'
    let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
    " }}}
    
    " Strip whitespace {{{
    nnoremap <F10> :execute StripTrailingWhitespace()<Cr>
    " }}}

    " PHP Code style fix {{{
    nnoremap <F11> :!php-cs-fixer fix %<Cr>
    " }}}
    
    " Multiple theme in case of eye strain   
    nnoremap <leader>1 :colorscheme obsidian<Cr>
    nnoremap <leader>2 :colorscheme Tomorrow-Night-Bright<Cr>
    nnoremap <leader>3 :colorscheme molokai<Cr>
    nnoremap <leader>4 :colorscheme badwolf<Cr>

" }}}

" Load user configuration {{{
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
" }}}
