#!/usr/bin/env bash
#
#  Note: this script requires passwordless access to
#        poweroff, reboot, pm-suspend and pm-hibernate
#


lock() {
  i3lock -c 2d2d31
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock && systemctl suspend
    ;;
  hibernate)
    lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
    exit 2
esac

exit 0
